apiVersion: ec2.aws.upbound.io/v1beta1
kind: InternetGateway
metadata:
  name: demo-igw
spec:
  forProvider:
    region: us-east-1

    vpcIdRef:
      name: demo-vpc

  providerConfigRef:
    name: default
