apiVersion: ec2.aws.upbound.io/v1beta2
kind: Route
metadata:
  name: public-default-route
spec:
  forProvider:
    region: us-east-1

    destinationCidrBlock: 0.0.0.0/0

    routeTableIdRef:
      name: public-rt

    gatewayIdRef:
      name: demo-igw

  providerConfigRef:
    name: default
